name: "🐞 Bug Report"
description: "Reporte um problema encontrado no sistema SmartLanche"
title: "[BUG] Descreva o problema"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## ⚠️ Descrição do problema"

  - type: textarea
    id: descricao
    attributes:
      label: "Descreva o bug"
      placeholder: "Explique o que aconteceu..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Passos para reproduzir"
      placeholder: "1. Vá até...\n2. Clique em...\n3. Observe o erro"
    validations:
      required: true

  - type: textarea
    id: comportamento_esperado
    attributes:
      label: "Comportamento esperado"

  - type: textarea
    id: evidencias
    attributes:
      label: "Evidências (prints, vídeo, logs)"
