name: "Solicitar Nova Funcionalidade"
description: "Use este template para sugerir novas funcionalidades."
labels: ["enhancement"]
body:
  - type: input
    id: feature
    attributes:
      label: "Descrição da funcionalidade"
      placeholder: "Explique a feature desejada..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivação"
      placeholder: "Por que isso é útil?"
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternativas Consideradas"
