name: "🚀 Feature Request"
description: "Sugira uma nova funcionalidade para o SmartLanche"
title: "[FEATURE] Descreva a funcionalidade"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## ✨ Nova funcionalidade"

  - type: textarea
    id: user_story
    attributes:
      label: "User Story"
      placeholder: "Como <tipo de usuário>, eu desejo <funcionalidade>, para <benefício>."
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: "Descrição detalhada da funcionalidade"
      placeholder: "Explique claramente o que deve ser implementado."

  - type: textarea
    id: alternativas
    attributes:
      label: "Alternativas consideradas"
      placeholder: "Liste outras possíveis abordagens."

  - type: textarea
    id: extras
    attributes:
      label: "Informações adicionais"
